<?php $megaMenu = $this->getMegamenuItems(); ?>
<?php $helper = $this->helper('MGS\Mmegamenu\Helper\Data') ?>
<?php if(count($megaMenu)>0):?>
	<ul id="horizontal-menu-<?php echo $this->getMenuId()?>" class="horizontal-menu nav nav-pills nav-main">
		<?php $i=0; foreach($megaMenu as $item): $i++ ?>
			<li class="<?php echo $this->getClass($item) ?>">
				<?php echo $helper->generateContentFilter($item->getSubContent()); ?>
			</li>
		<?php endforeach ?>
	</ul>
<?php endif ?>