<?php $themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config') ?>
<?php $category = $this->getCurrentCategory() ?>
<?php $themeSettingConfig = $this->getThemeSettingConfig() ?>
<?php $_categories = $category->getChildrenCategories(); ?>
<?php if(count($_categories)>0): ?>
<div class="landing-masonry ">
	
		<?php $i =0; foreach ($_categories as $_category): ?>
			<?php $_category = $block->getCategory($_category->getId()); ?>
			<?php if ($_category->getIsActive()): ?>
				<?php $i++; ?>
					<div class=" landing-masonry-item <?php if( $i%4 == 1 || $i%6 == 1 || $i%7 == 1 ) :?> widthx2 <?php endif; ?>" style="background-image: url('<?= $block->getImageUrl($_category->getFbuilderThumbnail()); ?>');">
						<div class="item-subcate">
							<div class="image-subcate">
								<a class="image" href="<?= $_category->getUrl() ?>" title="<?= $_category->getName() ?>">
									<img src="<?= $block->getImageUrl($_category->getFbuilderThumbnail()); ?>" alt="<?= $_category->getName() ?>" />
								</a>
								
							</div>
							<div class="info-subcate">
								<h3 class="title">
									<a href="<?= $_category->getUrl() ?>" title="<?= $_category->getName() ?>"><?= $_category->getName() ;?></a>
								</h3>
								<span class="sub-title">
									<?= __('%1 Products', $_category->getProductCount());?>
								</span>
								
							</div>
						</div>
					</div>
			<?php endif; ?>
		<?php endforeach ?>

</div>
<?php endif ?>
