<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');

switch ($type = $block->getType()) {

    case 'related-rule':
        if ($exist = $block->hasItems()) {
            $type = 'related';
            $class = $type;
			
			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;

            $image = 'related_products_list';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_title');
            $title = $titleConfig ? __($titleConfig) : __('Related Products');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type = 'related';
            $class = $type;
			
			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;

            $image = 'related_products_list';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/product_details/related_title');
            $title = $titleConfig ? __($titleConfig) : __('Related Products');
            $items = $block->getItems();
            $limit = 0;
            $shuffle = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo = true;
            $showCart = false;
            $templateType = null;
            $description = false;
        }
    break;

    case 'upsell-rule':
        if ($exist = $block->hasItems()) {
            $type = 'upsell';
            $class = $type;
			
			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;

            $image = 'upsell_products_list';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_title');
            $title = $titleConfig ? __($titleConfig) : __('We found other products you might like!');
            $items = $block->getAllItems();
            $limit = $block->getPositionLimit();
            $shuffle = (int) $block->isShuffled();

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'upsell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Upsell $block */
        if ($exist = count($block->getItemCollection()->getItems())) {
            $type = 'upsell';
            $class = $type;

			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;
			
            $image = 'upsell_products_list';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/product_details/upsell_title');
            $title = $titleConfig ? __($titleConfig) : __('We found other products you might like!');
            $items = $block->getItemCollection()->getItems();
            $limit = $block->getItemLimit('upsell');
            $shuffle = 0;

            $showAddTo = false;
            $showCart = false;
            $templateType = null;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type = 'crosssell';
            $class = $type;
			
			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;

            $image = 'cart_cross_sell_products';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_title');
            $title = $titleConfig ? __($titleConfig) : __('More Choices:');
            $title = __('');
            $items = $block->getItemCollection();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type = 'crosssell';
            $class = $type;

			$useSlider = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_slider');
			if($useSlider){
				$autoPlay = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_autoplay');
				$stopAutoPlayHover = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_stop_auto');
				$loop = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_loop');
				$nav = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_navigation');
				$dots = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_pagination');
				$slideBy = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_slide_by');
			}
			$perRowDefault = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row');
			$perRowTablet = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row_tablet');
			$perRowMobile = $themeSettingConfig->getStoreConfig('themesettings/product_details/crosssell_per_row_mobile');
            $classCol = ' row-' . $perRowDefault . ' row-tablet-' . $perRowTablet . ' row-mobile-' . $perRowMobile;
			
            $image = 'cart_cross_sell_products';
			$titleConfig = $themeSettingConfig->getStoreConfig('themesettings/shopping_cart/crosssell_title');
            $title = $titleConfig ? __($titleConfig) : __('More Choices:');
            $items = $block->getItems();

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = false;
            $canItemsAddToCart = false;
        }
    break;

    case 'new':
        if ($exist = $block->getProductCollection()) {
            $type = 'new';
            $mode = 'grid';
            $type = $type . ' ' . $mode;

			$useSlider = false;
            $class = 'widget' . ' ' . $type;
			$classCol = "";
			
            $image = 'new_products_content_widget_grid';
            $title = __('New Products');
            $items = $exist;

            $showAddTo = true;
            $showCart = true;
            $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description = ($mode == 'list') ? true : false;
            $canItemsAddToCart = false;
        }
    break;

    case 'other':
    break;
}
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php /* @escapeNotVerified */ echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php /* @escapeNotVerified */ echo $limit; ?>" data-shuffle="<?php /* @escapeNotVerified */ echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php /* @escapeNotVerified */ echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php /* @escapeNotVerified */ echo $class?>-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo $title; ?></strong>
    </div>
    <div class="block-content content <?php if(!$useSlider): ?><?php echo $classCol ?><?php endif ?>" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class?>-heading">
        <?php if ($type == 'related' && $canItemsAddToCart): ?>
        <div class="block-actions">
            <?php /* @escapeNotVerified */ echo __('Check items to add to the cart or') ?>
            <button type="button" class="action select" role="select-all"><span><?php /* @escapeNotVerified */ echo __('select all') ?></span></button>
        </div>
        <?php endif; ?>
        <div class="products wrapper grid products-grid<?php if($useSlider): ?> active-slider<?php endif ?> products-<?php /* @escapeNotVerified */ echo $type; ?>">
            <ol id="product-slider-<?php echo $type ?>" class="products list items product-items<?php if($useSlider): ?> owl-carousel<?php endif ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                <?php $available = ''; ?>
                <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <?php $available = 'related-available'; ?>
                    <?php endif; ?>
                <?php endif; ?>
                <?php if ($type == 'related' || $type == 'upsell'): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item" style="display: none;">' : '</li><li class="item product product-item" style="display: none;">' ?>
                <?php else: ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <?php endif; ?>
                <div class="product-item-info <?php /* @escapeNotVerified */ echo $available; ?>">
                    <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
                    <a href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                        <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>">
                            <?php echo $block->escapeHtml($_item->getName()) ?></a>
                        </strong>

                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item); ?>

                            <?php if ($templateType): ?>
                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
                            <?php endif; ?>

                            <?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
                                <?php if (!$_item->getRequiredOptions()): ?>
                                    <div class="field choice related">
                                        <input type="checkbox" class="checkbox related" id="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>" name="related_products[]" value="<?php /* @escapeNotVerified */ echo $_item->getId() ?>" />
                                        <label class="label" for="related-checkbox<?php /* @escapeNotVerified */ echo $_item->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span></label>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                            <?php if ($showAddTo || $showCart): ?>
                                <div class="product actions product-item-actions">
                                    <?php if ($showCart): ?>
                                        <div class="actions-primary">
                                            <?php if ($_item->isSaleable()): ?>
                                                <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                    <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php else: ?>
                                                    <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                    $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                    ?>
                                                    <button class="action tocart primary"
                                                            data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                            type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button>
                                                <?php endif; ?>
                                            <?php else: ?>
                                                <?php if ($_item->getIsSalable()): ?>
                                                    <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>

                                    <?php if ($showAddTo): ?>
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                                <?php echo $addToBlock->setProduct($_item)->getChildHtml(); ?>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
			<?php if($useSlider): ?>
				<script type="text/javascript">
					require([
						'jquery',
						'mgsowlcarousel'
					], function ($) {
						$('#product-slider-<?php echo $type ?>').owlCarousel({
							items: <?php echo $perRowDefault; ?>,
							autoplay: <?php echo $autoPlay ? 'true' : 'false' ?>,
							autoplayHoverPause: <?php echo $stopAutoPlayHover ? 'true' : 'false' ?>,
							nav: <?php echo $nav ? 'true' : 'false' ?>,
							dots: <?php echo $dots ? 'true' : 'false' ?>,
							loop: <?php echo $loop ? 'true' : 'false' ?>,
							<?php if($slideBy): ?>
							slideBy: <?php echo $slideBy ?>,
							<?php endif ?>
							lazyLoad: true,
							responsive:{
								0:{
									items: <?php echo $perRowMobile; ?>
								},
								768:{
									items: <?php echo $perRowTablet; ?>
								},
								992:{
									items: <?php echo $perRowDefault; ?>
								}
							}
						});
					});
				</script>
			<?php endif ?>
        </div>
    </div>
</div>
<?php endif;?>
