<?php $helper = $this->getHelper() ?>
<?php $usePanel = $helper->acceptToUsePanel() ?>
<?php if($helper->showButton()): ?>
	<?php $panelStyleUrl = $helper->getMediaUrl().'mgs/fbuilder/css/panel.css'; ?>
	<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $panelStyleUrl ?>" /> 
<?php endif ?>
<div class="panel wrapper top-panel" style="display:none">
	<div class="panel header builder-panel">
		<div class="left-content">
			<?php if($helper->acceptToUsePanel()): ?>
				<?php if($helper->isHomepage() || $helper->isCmsPage()): ?>
					<button class="action subscribe primary btn btn-default btn-panel-confirm" type="button" onclick="setLocation('<?php echo $helper->getUrlBuilder()->getUrl('fbuilder/index/confirm',['store_id'=>$this->getStoreId(),'page_id'=>$this->getCmsPageId(), 'page'=>$this->getRequest()->getFullActionName(),'referrer'=>$helper->getCurrentBase64Url()]) ?>')"><i class="fa fa-check"></i> <span><?php echo __('Publish') ?></span></button>
				<?php endif ?>
			<?php endif ?>
			<?php if($helper->getFullActionName()!='mgsthemesetting_theme_customize'): ?>
				<button class="action subscribe primary btn btn-default btn-panel-confirm" type="button" onclick="setLocation('<?php echo $helper->getUrlBuilder()->getUrl('mgsthemesetting/theme/customize',['referrer'=>$helper->getCurrentBase64Url()]) ?>')" style="margin-left:10px"><i class="fa fa-pencil"></i> <span><?php echo __('Customize') ?></span></button>
			<?php endif ?>
		</div>
		<div class="right-content">
			<?php if($helper->getFullActionName()!='mgsthemesetting_theme_customize'): ?>
				<div data-role="switcher" class="admin__actions-switch pull-right">
					<?php if($usePanel): ?>
						<input type="checkbox" class="admin__actions-switch-checkbox" value="1" id="active-fbuilder" checked="checked" onclick="setLocation('<?php echo $helper->getUrlBuilder()->getUrl('fbuilder/index/disable',['referrer'=>$helper->getCurrentBase64Url()]) ?>')"/>
					<?php else: ?>
						<input type="checkbox" class="admin__actions-switch-checkbox" value="0" id="active-fbuilder" onclick="setLocation('<?php echo $helper->getUrlBuilder()->getUrl('fbuilder/index/active',['referrer'=>$helper->getCurrentBase64Url()]) ?>')"/>
					<?php endif; ?>
					<label class="admin__actions-switch-label" for="active-fbuilder">
						<span class="admin__actions-switch-text" data-text-on="<?php echo __('Yes') ?>" data-text-off="<?php echo __('No') ?>"></span>
					</label>
				</div>
				<span class="builder-switcher-label pull-right"><?php echo __('Active CMS Builder') ?></span>
			<?php endif ?>
		</div>
		<?php if($helper->getFullActionName()=='mgsthemesetting_theme_customize'): ?>
			<div class="theme-info"></div>
			<div class="responsive-action">
				<ul>
					<li><button class="responsive" data-responsive="phone"><span class="pe-7s-phone"></span></button></li>
					<li><button class="responsive active" data-responsive="desktop"><span class="pe-7s-monitor"></span></button></li>
					<li><button class="responsive" data-responsive="full"><span class="pe-7s-expand1"></span></button></li>
				</ul>
			</div>
			<button class="action subscribe primary btn btn-default btn-panel-confirm" title="<?php echo __('Close') ?>" type="button" onclick="setLocation('<?php echo $helper->getUrlBuilder()->getUrl('mgsthemesetting/theme/close',['referrer'=>$helper->getCurrentBase64Url()]) ?>')" style="margin-left:10px"><span class="pe-7s-close"></span></button>
		<?php endif ?>
	</div>
</div>
<?php if($helper->acceptToUsePanel()): ?>
	<script  type="text/javascript" src="<?php echo $this->getViewFileUrl('MGS_Fbuilder::js/panel.js') ?>"></script>
<?php endif ?>
<script>
	require([
        'jquery'
    ], function($) {
		if(self!=top){
			$('.top-panel').remove();
		}else{
			if($('#themesetting_customize_temp').length){
				$('#themesetting_customize_temp').remove();
			}

			<?php if($helper->isCustomize() && ($helper->getFullActionName()!='mgsthemesetting_theme_customize')): ?>
				$.ajax({url: '<?php echo $this->getUrl('mgsthemesetting/theme/close') ?>'});
			<?php endif ?>
		}
    });
</script>