<?php
$helper = $this->helper('MGS\Guestwishlist\Helper\Data');
if($this->getWishlistParam()){
	$items = $helper->getWishlistItemCollection(NULL,$this->getWishlistParam());
}else {
	$items = $helper->getWishlistItemCollection();
}
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');

$image = 'wishlist_thumbnail';
?>

<div id="guest_wishlist_list" class="products wrapper wishlist grid products-grid">
    <?php $iterator = 1; ?>
    <?php if (count($items)): ?>
		<form class="form-wishlist-items" id="wishlist-view-form" action="<?php echo $this->getUrl('guestwishlist/index/updateall'); ?>" method="post" novalidate="novalidate">
			<input type="hidden" id="guest_status" name="guest_status" value="1">
            <ol class="product-items row row-wrapper row-4">
                <?php foreach ($items as $item): ?>
                    <?php
                    $_product = $item['product'];
                    $productUrl = $_product->getUrlModel()->getUrl($_product, []);
                    ?>
                    <li class="product-wishlist-items item product product-item  col">
						<input type="number" data-role="qty" id="qty[<?= $_product->getId() ?>]" class="input-text qty" data-validate="{'required-number':true,'validate-greater-than-zero':true}" name="qty[<?= $_product->getId() ?>]" value="<?= $item['qty'] ?>">
						
						<input type="hidden" id="item_id[<?= $_product->getId() ?>]" class="input-text qty" name="item_id[<?= $_product->getId() ?>]" value="<?= $item['item_id'] ?>">
						
						<textarea id="product-item-comment-<?= $_product->getId() ?>" placeholder="Comment" name="description[<?= $_product->getId() ?>]" title="Comment" class="product-item-comment"><?php echo $item['description'] ?></textarea>
						
						<div class="product-item-info" data-container="product-grid">
							<div class="product-item-image">
								<?php $productImage = $_imagehelper->init($_product, $image)->getUrl(); ?>
								<a href="<?php echo $block->escapeUrl($productUrl) ?>" class="product photo product-item-photo" tabindex="-1">
									<img style="position: static;" src="<?php echo $productImage ?>" alt="<?php echo $block->stripTags($_product->getName(), null, true); ?>" class="img-fluid product-image-photo"/>
								</a>
								<?php if ($_product->isSaleable()): ?>
									<div class="product-item-actions">
                                        <div class="actions-primary">
                                            <button type="button" data-role="tocart" data-post='<?php echo $item['data_post'] ?>' title="<?php echo __('Add to Cart') ?>" data-item-id="<?php echo $item['item_id'] ?>" class="action primary">
                                                <i class="fa fa-shopping-cart"></i>
                                            </button>
                                        </div>
                                    </div>
								<?php endif ?>
							</div>
							<div class="product details product-item-details">
								<h5 class="product name product-item-name">
									<a class="product-item-link" href="<?php echo $block->escapeUrl($productUrl) ?>"><?php echo $block->stripTags($_product->getName(), null, true); ?></a>
								</h5>	
								<div class="product-buy_info">
									<div class="price-box price-configured_price">
										<p class="price-as-configured">
											<span class="price-container price-configured_price tax weee">
												<span data-price-type="finalPrice" class="price-wrapper ">
													<span class="price"><?php echo $helper->formatPrice($_product->getFinalPrice()) ?></span>
												</span>
											</span>
										</p>
									</div>
									<button class="action primary remove" href="javascript:void(0);" data-action="remove-from-wishlist" data-url='<?php echo $helper->getDeleteItemParams($item, $_product, $block->stripTags($_product->getName(), null, true)) ?>'><span class="ti-trash"></span></button>
								</div>
							</div>
							<?php if (isset($item['wishlist_options'])): ?>
								<div class="product-item-tooltip">
									<?php echo $item['wishlist_options']; ?>
								</div>
							<?php endif; ?>
						</div>
                    </li>
                <?php endforeach; ?>
            </ol>
			<button id="update_all_wishlist" type="submit" title="Update Wish List" class="action update">
				<span>Update Wish List</span>
			</button>
		</form>
    <?php else: ?>
        <div class="message info empty">
            <span><?= $block->escapeHtml(__('This Wish List has no Items')) ?></span>
        </div>
    <?php endif; ?>
</div>
