<?php
$helper = $this->helper('MGS\Blog\Helper\Data');
$collection = $block->getCollection();
?>
<?php if($this->getRequest()->getParam('id')){
	$checkParam = true;
	$id_param = $this->getRequest()->getParam('id');
}else{
	$checkParam = false;
}
$themeSettingConfig = $this->helper('MGS\ThemeSettings\Helper\Config');
$rtl = $themeSettingConfig->getStoreConfig('themesettings/general/rtl_theme') ? 'true' : 'false';
?>
<?php if (!count($collection)): ?>
    <div class="message empty">
        <div><?= __('Have no posts.') ?></div>
    </div>
<?php else: ?>
	<div class="all-category">
		<?php $categories = $block->getCategories(); ?>
		<?php if (count($categories)): ?>
			<div class="block block-blog-categories">
				<ul class="block-content">
					<li>
						<a class="active" href="<?= $block->getUrl('blog'); ?>">
							<?= __('All Categories') ?>
						</a>
					</li>
					<?php foreach ($categories as $category): ?>
						<li>
							<a title="<?= $category->getTitle(); ?>"
							   href="<?= $category->getCategoryUrl(); ?>">
								<?= $category->getTitle(); ?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			</div>
		<?php endif; ?>
	</div>
    <div class="blog-grid blog-post-item">
		<div class="line">
			<?php  foreach ($collection as $post):?>
				<div class="item col-des-4 col-tb-6 col-mb-12 mg-top-55">
					<div class="post-images">
						<?php if ($helper->getGalleryImage($post)): ?>
							<div class="post-thumbnail gallery-image-carousel owl-carousel">
								<?php foreach($helper->getGalleryImage($post) as $_img): ?>
									<a class="post-thumbnail--image gallery_image" href="<?= $_img; ?>" 
										style="background-image: url('<?= $_img; ?>')">
										<img src="<?= $_img; ?>" alt="" class="img-fluid"/>
									</a>
								<?php endforeach ?>
							</div>
							<script type="text/javascript">
								require([
									'jquery',
									'mgsowlcarousel'
									], function($){			
										$(document).ready(function(){
											$(".gallery-image-carousel").owlCarousel({
												items: 10,
												loop: true,
												nav: false,
												dots: false,
												autoplayTimeout: 5000,
												rtl: <?= $rtl ?>,
												autoplay: true,
												autoplayHoverPause: true,
												margin: 0,
												autoHeight:true,
												responsive:{
													0:{
														items: 1
													},
													576:{
														items: 1
													},
													767:{
														items: 1
													},
													992:{
														items: 1						
													}
												}
											});
										});  	
									});		
								
								require([
									'jquery',
									'magnificPopup'
								], function(jQuery){
									(function($) {
										$(document).ready(function() {
											$('.gallery-image-carousel').magnificPopup({
												delegate: '.owl-item:not(.cloned) a',
												type: 'image',
												tLoading: 'Loading image #%curr%...',
												mainClass: 'mfp-img-gallery',
												fixedContentPos: true,
												gallery: {
													enabled: true,
													navigateByImgClick: true,
													preload: [0,1]
												},
												image: {
													tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
													titleSrc: function(item) {
													return item.el.attr('title');
													}
												}
											});
										});
									})(jQuery);
								});
							</script>
							<?php else:?> 
							<?php if($helper->getImageThumbnailPost($post) != ""): ?>
								<div class="post-thumbnail">
									<?php if($post->getThumbType() == "video" && $post->getVideoThumbId() != ""): ?>
										<a class="post-thumbnail--image popup-video" href="<?= $helper->getVideoThumbUrl($post); ?>" 
										style="background-image:url('<?= $helper->getImageThumbnailPost($post); ?>');" title="<?= $post->getTitle(); ?>">
											<img class="img-fluid" src="<?= $helper->getImageThumbnailPost($post); ?>" alt="<?= $post->getTitle(); ?>"/>
										</a>
										<div class="blog-list-video">
											<?php if($post->getThumbType() == "video" && $post->getVideoThumbId() != ""): ?>
												<a class="btn btn-primary popup-video" href="<?= $helper->getVideoThumbUrl($post); ?>"></a>
											<?php endif ?>
										</div>	
									<?php else: ?>
										<a class="post-thumbnail--image" style="background-image:url('<?= $helper->getImageThumbnailPost($post); ?>');" href="<?= $post->getPostUrlWithNoCategory(); ?>" title="<?= $post->getTitle(); ?>">
										<img class="img-fluid" src="<?= $helper->getImageThumbnailPost($post); ?>" alt="<?= $post->getTitle(); ?>"/>
										</a>
								<?php endif ?>
								</div>
							<?php endif ?>
						<?php endif ?>
						<div class="post-metas">
							<a class="link-item" href="<?= $post->getPostUrlWithNoCategory(); ?>" title="<?= $post->getTitle(); ?>"><?= $post->getTitle() ?> </a>
							<div class="meta-date">
								<span class="color-theme"><?= $post->getUser(); ?></span>
								<span class="color-date"><?= $block->formatDate($post->getCreatedAt(), \IntlDateFormatter::MEDIUM, false); ?></span>
							</div>
						</div>	
					</div>	
				</div>
			<?php endforeach; ?>
		</div>
		<div class="bottom-pagination text-center">
			<div class="toolbar"><?= $block->getPagerHtml(); ?></div>
		</div>
		<?= $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('supro_newsletter_blog_page')->toHtml();?>
	</div>
<?php endif; ?>
<script type="text/javascript">
	require([
		'jquery',
		'magnificPopup'
	], function(jQuery){
		(function($) {
			$(document).ready(function() {
				$('.popup-video').magnificPopup({
					disableOn: 700,
					type: 'iframe',
					mainClass: 'mfp-img-gallery',
					removalDelay: 160,
					preloader: false,
					fixedContentPos: false
				});
			});
		})(jQuery);
	});
</script>

